services:
  cassandra:
    image: cassandra
    container_name: cassandra
    restart: always
    ports:
      - "9042:9042"
  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra
    depends_on:
      - cassandra
    volumes:
      - ./init.cql:/init.cql
    command: /bin/bash -c "cqlsh cassandra -f /init.cql"